### master
master:
  build: ./master
  hostname: master
  ports:
   - "192.168.99.101:9000:9000" # NameNode
   - "192.168.99.101:50070:50070" # NameNode dfs.namenode.http-address
   - "192.168.99.101:50090:50090" # Secondary Namenode
   - "192.168.99.101:50010:50010" # DataNode dfs.datanode.address
   - "192.168.99.101:50020:50020" # DataNode
   - "192.168.99.101:50030:50030" # mapreduce.jobtracker.http.address
   - "192.168.99.101:50075:50075" # dfs.datanode.http.address
   - "192.168.99.101:8088:8088" # ResourceManager
   - "192.168.99.101:8030:8030" # ResourceManager
   - "192.168.99.101:8031:8031" # ResourceManager
   - "192.168.99.101:8032:8032" # ResourceManager
   - "192.168.99.101:8033:8033" # ResourceManager
   - "192.168.99.101:8040:8040" # NodeManager
   - "192.168.99.101:8042:8042" # NodeManager
   - "192.168.99.101:42954:42954" # NodeManager
   - "192.168.99.101:13562:13562" # NodeManager
   - "192.168.99.101:19888:19888" # JobHistory
   - "192.168.99.101:2122:2122" # SSH


#
#### cluster
#zookeeper:
#  image: jplock/zookeeper
#  ports:
#    - "2181:2181"
#nimbus:
#  image: wurstmeister/storm-nimbus:0.9.2
#  ports:
#    - "3773:3773"
#    - "3772:3772"
#    - "6627:6627"
#  links:
#    - zookeeper:zk
#supervisor:
#  image: wurstmeister/storm-supervisor:0.9.2
#  ports:
#    - "8000:8000"
#  links:
#    - nimbus:nimbus
#    - zookeeper:zk
#ui:
#  image: wurstmeister/storm-ui:0.9.2
#  ports:
#    - "8080:8080"
#  links:
#    - nimbus:nimbus
#    - zookeeper:zk
#kafka1:
#  image: wurstmeister/kafka:0.8.2.0
#  ports:
#    - "9092:9092"
#  links:
#    - zookeeper:zk
#  environment:
##    HOST_IP: 192.168.99.101
##    PORT: 9092
#    KAFKA_HOST_NAME: stormkafkadocker_kafka1_1
#    KAFKA_BROKER_ID: 1
#  volumes:
#    - /var/run/docker.sock:/var/run/docker.sock
#kafka2:
#  image: wurstmeister/kafka:0.8.2.0
#  ports:
#    - "9093:9092"
#  links:
#    - zookeeper:zk
#  environment:
##    HOST_IP: 192.168.99.101
##    PORT: 9092
#    KAFKA_HOST_NAME: stormkafkadocker_kafka2_1
#    KAFKA_BROKER_ID: 2
#  volumes:
#    - /var/run/docker.sock:/var/run/docker.sock
##openfire:
##  image: mdouglas/openfire
##  ports:
##  - "5222:5222"
##  - "5223:5223"
##  - "9091:9091"
##  - "9090:9090"
